import type { Metadata } from "next";
import { Navbar } from "@/src/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
          <Navbar>{children}</Navbar>
      </body>
    </html>
  );
}
